<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="vote">
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('User'); ?></th>
			<th><?php _e('Module'); ?></th>
			<th><?php _e('Item'); ?></th>
			<th><?php _e('Create'); ?></th>
		</tr>
		<?php foreach($votes as $vote) { ?>
		<tr>
			<td><?php echo $this->escape($vote['id']); ?></td>
			<td><?php echo $this->escape($vote['identity']); ?></td>
			<td><?php echo $this->escape($vote['module']); ?></td>
			<td><?php echo $this->escape($vote['item']); ?></td>
			<td><?php echo $this->escape($vote['create']); ?></td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
</div>