<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('List score options'); ?></h3>
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Module'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($list as $score) { ?>
            <?php if ($score['status'] == 1) {
                $labelIdClass = 'label-success';
            } else {
                $labelIdClass = 'label-warning';
            } ?>
            <tr>
                <td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($score['id']); ?></span>
                </td>
                <td><?php echo $this->escape($score['title']); ?></td>
                <td><?php echo $this->escape($score['module_view']); ?></td>
                <td>
                    <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                       href="<?php echo $this->url('', ['action' => 'update', 'id' => $score['id']]); ?>"><i
                                class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                </td>
            </tr>
        <?php } ?>
    </table>
</div>