<?php
$this->jquery();
$this->js($this->assetModule('script/plus.js', 'vote'));
$vote['point'] = (!empty($vote['point'])) ? _number($vote['point']) : _number(0);
if($vote['point'] > 0) {
	$pointClass = 'btn-success';	
} elseif($vote['point'] < 0) {
	$pointClass = 'btn-danger';	
} else {
	$pointClass = 'btn-default';	
}
?>
<div id="votebar-<?php echo $vote['module']; ?>-<?php echo $vote['table']; ?>-<?php echo $vote['item']; ?>" class="clearfix votebar btn-group <?php if(isset($vote['class'])) {echo $vote['class'];} ?>">
	<a class="btn btn-default btn-sm" id="vote-<?php echo $vote['module']; ?>-<?php echo $vote['table']; ?>-<?php echo $vote['item']; ?>-up" onclick="Set_Vote({to: '<?php echo $vote['module']; ?>', item: '<?php echo $vote['item']; ?>', vote: '1', table: '<?php echo $vote['table']; ?>'}, '<?php echo Pi::url('vote', true); ?>', '<?php echo $vote['item']; ?>', '<?php echo $vote['table']; ?>', '<?php echo $vote['module']; ?>');"><i class="fa fa-thumbs-up"></i></a>
	<a class="btn <?php echo $pointClass; ?> btn-sm" id="vote-<?php echo $vote['module']; ?>-<?php echo $vote['table']; ?>-<?php echo $vote['item']; ?>-do"><?php echo $vote['point']; ?></a>
	<a class="btn btn-default btn-sm" id="vote-<?php echo $vote['module']; ?>-<?php echo $vote['table']; ?>-<?php echo $vote['item']; ?>-down" onclick="Set_Vote({to: '<?php echo $vote['module']; ?>', item: '<?php echo $vote['item']; ?>', vote: '-1', table: '<?php echo $vote['table']; ?>'}, '<?php echo Pi::url('vote', true); ?>', '<?php echo $vote['item']; ?>', '<?php echo $vote['table']; ?>', '<?php echo $vote['module']; ?>');"><i class="fa fa-thumbs-down"></i></a>
</div>