<?php if (isset($vote) && !empty($vote)) {
	switch ($vote['type']) {
		case 'plus':
		    include $this->template('plus', 'front', 'vote');
			break;

		case 'star':
            if (isset($vote['score']) && count($vote['score']) > 1) {
                include $this->template('stars', 'front', 'vote');
            } else {
                include $this->template('star', 'front', 'vote');
            }
			break;
	}
} ?>